project:
  type: website

website:
  title: "cambio-climatico"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-tools: true
    html-math-method: mathjax
    
editor: visual

